### ISSUE TITLE
APPGW - check if we can add NICs instead of IPs to backed pool

### ISSUE THREAD

**Issue by sebastianczech** [PaloAltoNetworks/terraform-azurerm-swfw-modules#16]

**Comment by sebastianczech** [comment]
According to official documentation, [Application Gateway backend pool supports](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-components):
- NICs
- Virtual machine scale sets
- Public IP addresses
- Internal IP addresses
- FQDN
- Multitenant backends (such as App Service)

**Comment by acelebanski** [comment]
Thanks for the solid research @sebastianczech, I'm closing the issue then.
