### ISSUE TITLE
add `EOF` notation to all `error_message` strings in `validation` and `precondition` blocks

### ISSUE THREAD

**Issue by sebastianczech** [PaloAltoNetworks/terraform-azurerm-swfw-modules#17]

**Comment by acelebanski** [comment]
Hey @sebastianczech, I started correcting validation blocks in `var_grouping_for_lbs` branch. I'm also adding validation descriptions. I took over this issue, hope you don't mind.

**Comment by sebastianczech** [comment]
hey @acelebanski ok
