### ISSUE TITLE
Add support for Azure Virtual Network encryption

### ISSUE THREAD

**Issue by jinkang23** [PaloAltoNetworks/terraform-azurerm-swfw-modules#52]
As of 4/16/24, Azure Virtual Network encryption is generally available across all regions. 

[VNET submodule](https://github.com/PaloAltoNetworks/terraform-azurerm-swfw-modules/tree/main/modules/vnet), however, does not allow passing in configuration to enable VNET encryption. 

Please add support to optionally enable encryption on Azure VNET resource. 

Here's an example of how to enable encryption on `azurerm_virtual_network` resource:  
```hcl
resource "azurerm_virtual_network" "this" {
  count = var.create_virtual_network ? 1 : 0

  name                = var.name
  location            = var.region
  resource_group_name = var.resource_group_name
  address_space       = var.address_space

  # ADDED ENCRYPTION BLOCK
  encryption {
    enforcement = "AllowUnencrypted"
  }

  tags                = var.tags

  lifecycle {
    precondition {
      condition     = length(coalesce(var.address_space, [])) > 0
      error_message = "The `var.address_space` property is required when creating a VNET."
    }
  }
}


```

**Comment by acelebanski** [comment]
Hello @jinkang23, thank you for raising this feature request. It will be introduced in the next release by PR #54.

**Comment by jinkang23** [comment]
Perfect! Thank you @acelebanski
