### ISSUE TITLE
Add support for Capacity Reservation Group on VMSS ScaleSet resource in `vmss` sub-module

### ISSUE THREAD

**Issue by jinkang23** [PaloAltoNetworks/terraform-azurerm-swfw-modules#58]
### Is your feature request related to a problem?

In `vmss` sub-module, `azurerm_linux_virtual_machine_scale_set` resource does not allow a way to specify a Capacity Reservation group. On-demand Capacity Reservation enables us to reserve Compute capacity in an Azure region or an Availability Zone for any duration of time, and ensures that there's always capacity as the NVAs scale in and out.  

### Describe the solution you'd like

Here's an example of adding `capacity_reservation_group_id` to `azurerm_linux_virtual_machine_scale_set` resource:  

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "this" {
  name                 = var.name
  computer_name_prefix = null
  location             = var.region
  resource_group_name  = var.resource_group_name

  ...<omitted>...  

  encryption_at_host_enabled    = var.virtual_machine_scale_set.encryption_at_host_enabled
  overprovision                 = var.virtual_machine_scale_set.overprovision
  extension_operations_enabled  = var.virtual_machine_scale_set.allow_extension_operations
  platform_fault_domain_count   = var.virtual_machine_scale_set.platform_fault_domain_count
  single_placement_group        = var.virtual_machine_scale_set.single_placement_group


  capacity_reservation_group_id = var.virtual_machine_scale_set.capacity_reservation_group_id 

.. <omitted>... 

}
```

**Comment by acelebanski** [comment]
Hi @jinkang23, thanks for raising this feature request. This will be added by PR #73 and should be released soon!
