### ISSUE TITLE
Add LB ID in loadbalancer submodule output

### ISSUE THREAD

**Issue by traittinen** [PaloAltoNetworks/terraform-azurerm-swfw-modules#63]
### Is your feature request related to a problem?

Adding azurerm_lb ID in module output would help building e.g. metric alerts and NAT rules that require LB ID when defining resource.

### Describe the solution you'd like

output.tf

```
output "lb_id" {
  description = "The identifier of the load balancer."
  value       = azurerm_lb.this.id
}
```

**Comment by acelebanski** [comment]
Hello @traittinen, thanks for opening this feature request. Surely this is something we can do! The requested output will be added by PR #69 and should be released soon!
