### ISSUE TITLE
For `vnet` submodule with `azurerm_route_table` resource, property `disable_bgp_route_propagation` has been superseded by the property `bgp_route_propagation_enabled` and will be removed in v4.0 of the AzureRM Provider.

### ISSUE THREAD

**Issue by jinkang23** [PaloAltoNetworks/terraform-azurerm-swfw-modules#79]
### Is your feature request related to a problem?

For `vnet` submodule with `azurerm_route_table` resource, property `disable_bgp_route_propagation` has been superseded by the property `bgp_route_propagation_enabled` and will be removed in v4.0 of the AzureRM Provider. 

### Describe the solution you'd like

Update `azurerm_route_table` resource and replace the deprecated property  `disable_bgp_route_propagation` to `bgp_route_propagation_enabled`

**Comment by acelebanski** [comment]
Hi @jinkang23, thanks for raising this. We're aware of the properties being deprecated. There's actually more of them and they show up regularly, apparently v4.0 will be a big shift in naming convention. We are going to update all properties before they become out of use.
