### ISSUE TITLE
Add useable bootstrap parameters. 

### ISSUE THREAD

**Issue by jollymahn** [PaloAltoNetworks/terraform-azurerm-swfw-modules#90]
### Is your feature request related to a problem?

"type=dhcp-client" doesnt bootstrap the firewall. 

### Describe the solution you'd like

use the license plugin or basic bootstrap and provide a useable example. 
provide commented links in the config

Add a the following lines:
#License plugin
#https://docs.paloaltonetworks.com/vm-series/10-2/vm-series-deployment/license-the-vm-series-firewall/use-panorama-based-software-firewall-license-management
#Install device certificate
#https://docs.paloaltonetworks.com/vm-series/10-2/vm-series-deployment/license-the-vm-series-firewall/vm-series-models/install-a-device-certificate-on-the-vm-series-firewall

insert a real bootstrap example

https://github.com/PaloAltoNetworks/terraform-azurerm-swfw-modules/blob/6cc5eb460955bc03caab10f625088e263e7f3886/examples/common_vmseries/example.tfvars#L234

    bootstrap_options = "type=dhcp-client;plugin-op-commands=panorama-licensing-mode-on;auth-key=<YOUR-AUTH-KEY-HERE>;tplname=<YOUR-TEMPLATE-STACK-NAME-HERE>;dgname=<YOUR-DEVICE-GROUP-NAME-HERE>;vm-series-auto-registration-pin-id=<YOUR-PIN-ID-HERE>;vm-series-auto-registration-pin-value=<YOUR-PIN-VALUE-HERE>"

### Additional context

What is published for bootstrapping is crap. The goal is for the customer to be successful. Give us a pathway to success.

**Comment by acelebanski** [comment]
This issue duplicates #50. We're working on that.
