### ISSUE TITLE
Add support for `ddos_protection_plan` in vnet sub-module

### ISSUE THREAD

**Issue by jinkang23** [PaloAltoNetworks/terraform-azurerm-swfw-modules#92]
### Is your feature request related to a problem?

In our Azure environment, we assign DDoS Network Protection Plan to any Virtual Networks with Azure Public IPs. Since the Hub NGFW Firewall VM Series have a network interface with Public IP associated, we need to be able to set and enable DDoS protection plan in the `azurerm_virtual_network` resource.  Currently configuration is not available in the `vnet` sub-module. 

 I would like to see support for optionally specifying the `ddos_protection_plan` block in the `azurerm_virtual_network` resource within the vnet sub-module.

### Describe the solution you'd like

```hcl
variable "ddos_protection_plan" {
  type = object({
    id = string 
    enable = bool
  })
  default = null
}


resource "azurerm_virtual_network" "this" {
  count = var.create_virtual_network ? 1 : 0

  ...

  dynamic "ddos_protection_plan" {
    for_each = var.ddos_protection_plan != null ? [1] : []
    content {
      id = ddos_protection_plan.value.id
      enable = ddos_protection_plan.value.enable
    }
  }

  ...

}

```  

### Describe alternatives you've considered.

None

**Comment by acelebanski** [comment]
Hello @jinkang23, we discussed internally whether we should implement this and we decided to do it. The module will not create the DDOS Protection Plan but will be able to use an existing one by specifying its name and resource group name. This will be implemented with PR #107. Thank you.
